# Build Stage  
FROM microsoft/aspnetcore-build as build-env
WORKDIR /source
COPY . .  
RUN dotnet restore  
RUN dotnet publish -o /app --configuration Release  
  
# Publish Stage  
FROM microsoft/aspnetcore  
WORKDIR /app  
COPY --from=build-env /app .  
ENTRYPOINT ["dotnet", "DCore-Console.dll"]  